SECRET_KEY_BASE: 1eb2cb0ce50db81551c727fd20cd0b7b62260eadbf1459e7380d417dc5b6af30536e52f990f9dcd58bb15b60063e9e515b86decff639fab35589ba2a1adfc3d7
SERVER_URL: 'localhost:3001'
PASSWORD_RESET_URL: 'http://127.0.0.1:3001'
SENDGRID_USERNAME: 'kuuikdev'
SENDGRID_PASSWORD: '617738JacksonSky'
AWS_ACCESS_KEY_ID: 'AKIAJFR4XO33JAQW3UCA'
AWS_SECRET_ACCESS_KEY: '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'
S3_BUCKET_NAME: 'spidagram'
AWS_BUCKET_REGION: 'us-west'
STRIPE_TEST_PUB_KEY: 'pk_test_ss59FzBRW4YGFcNSvR1tqzL500q4TPoxNn'
STRIPE_TEST_KEY: 'sk_test_GckOEuRsY2Yr77oWzU7R5azS00gfEsbdeu'
